import { type NextPage } from "next";
import Head from "next/head";
import className from "classnames";
import { api } from "../utils/api";
import Spinner from "../components/Spinner";
import Image from "next/image";

const Home: NextPage = () => {
  const human = api.human.getHumanByUsername.useQuery({ username: "deepto" });

  return (
    <>
      <Head>
        <title>Deepto's Clab</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {human.isLoading && <Spinner />}

      {human.data && (
        <div className="max-w-[615px]">
          {/* Header Image */}
          <div className="aspect-w-3 aspect-h-1 bg-red-200 text-center">
            {human.data.header && (
              <Image
                alt="header"
                width={615}
                height={205}
                src={human.data.header}
              />
            )}
          </div>
          <div className="px-6 pt-2">
            <div className="flex">
              <div className="relative shrink-0 basis-[100px]">
                {/* Image Avatar */}
                <div
                  className={className(
                    // Conditional style
                    "absolute top-[-50px] box-content h-[100px] w-[100px] overflow-hidden rounded-full border-4 border-white bg-red-300",
                    { "border-opacity-25 bg-clip-padding": human.data.avatar }
                  )}
                >
                  {human.data.avatar && (
                    <Image
                      width={100}
                      alt="Human.jpg"
                      height={100}
                      src={human.data.avatar}
                    />
                  )}
                </div>
              </div>
              {/* Load the data from human */}
              <div className="relative ml-3.5 min-w-0">
                <p className="text-xl">{human.data.name}</p>
                <p className="overflow-hidden text-ellipsis text-xs">
                  {human.data.address}
                </p>
              </div>
            </div>
            <div className="mt-7">{human.data.summary}</div>
            <div className="mt-3.5 flex">
              <p>
                <span className="font-semibold">
                  {human.data.followersCount}
                </span>
                &nbsp;Followers
              </p>
              <p>
                <span className="ml-5 font-semibold">
                  {human.data.followingCount}
                </span>
                &nbsp;Following
              </p>
            </div>
          </div>
          {/* Posts, Replies Tabs */}
          <div className="border-b-2 border-neutral-50 mt-3.5 flex h-10 space-x-3.5 overflow-auto">
            <div className="flex h-full shrink-0 items-center rounded-t-lg bg-red-100 px-6 ml-3.5">
              <p className="font-semibold text-red-700">Posts</p>
            </div>
            <div className="flex h-full shrink-0 items-center rounded-t-lg px-6">
              <p className="font-semibold text-neutral-600">Posts & Replies</p>
            </div>
            <div className="flex h-full shrink-0 items-center rounded-t-lg px-6">
              <p className="font-semibold text-neutral-600">Likes</p>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default Home;
